# Generated by Django 5.0.3 on 2026-03-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
