# Generated by Django 5.2.11 on 2026-03-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
